name: Build And Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Windows Installer
        run: npx electron-builder --win

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-installers
          path: dist/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build macOS Installer
        run: npx electron-builder --mac

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-installers
          path: dist/*.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Linux Installer
        run: npx electron-builder --linux

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-installers
          path: dist/*.{AppImage,deb}
